// @flow
type Config = {
  size: string | number | void,
  sizes: [string | number] | void,
  min: string | number | void,
  max: string | number | void,
  steps: string | number | void,
  name?: string,
  outputPath: Function | string | void,
  publicPath: Function | string | void,
  context?: string,
  placeholder: string | boolean | void,
  placeholderSize: string | number | void,
  quality: string | number | void,
  background: string | number | void,
  progressive: boolean | void,
  adapter: ?Function,
  format: "png" | "jpg" | "jpeg" | "webp",
  disable: ?boolean,
  esModule?: boolean,
  emitFile?: boolean,
};
type ParsedConfig = {
  outputContext: string,
  outputPlaceholder: boolean,
  placeholderSize: number,
  quality: number,
  background?: string | number,
  progressive?: string | boolean,
  name: string,
  mime: string,
  ext: string,
  generatedSizes?: number[],
  esModule: boolean,
  emitFile: boolean,
};
export type { Config, ParsedConfig };
